apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../components/namespaces
  - ../../apps/platform-api
  - ../../apps/platform-web
  - ../../apps/validation-worker
  - ../../policies/opa
  - ../../observability
